# Change these first
owner: cardano-foundation
repo: cf-cip1694-ballot-status

sites:
  - name: 1694ballot.cardano.org
    url: https://1694ballot.cardano.org/
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'Cardano Voting Application'
    expectedStatusCodes:
      - 200
  - name: event-api
    url: https://follower-api.1694ballot.cardano.org/api/reference/event/CIP-1694_Pre_Ratification_TEST_2
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'CIP-1694_Pre_Ratification_TEST_2'
    expectedStatusCodes:
      - 200
  - name: blockchain-follower-api
    url: https://follower-api.1694ballot.cardano.org/api/blockchain/tip
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'absoluteSlot'
    expectedStatusCodes:
      - 200
  - name: login-api
    url: http://api.1694ballot.cardano.org/api/auth/login
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'Full authentication is required to access this resource'
    expectedStatusCodes:
      - 401
  - name: cast-vote-api
    url: http://api.1694ballot.cardano.org/api/vote/cast
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'Full authentication is required to access this resource'
    expectedStatusCodes:
      - 401
  - name: get-votes-api
    url: http://api.1694ballot.cardano.org/api/vote/votes/CIP-1694_Pre_Ratification_TEST_2
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'Full authentication is required to access this resource'
    expectedStatusCodes:
      - 401
  - name: get-vote-receipt-api
    url: http://api.1694ballot.cardano.org/api/vote/receipt/CIP-1694_Pre_Ratification_TEST_2/AMBASSADOR
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'Full authentication is required to access this resource'
    expectedStatusCodes:
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  cname: status.1694ballot.cardano.org
  #baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: cf-cip1694-ballot-status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


